version: '3'
services:
  web:
    image: node:18 # Use an appropriate Node.js version
    container_name: my-node-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    command: npm run dev
    env_file:
      - .env
